2022-02-13 17:24:04,667 INFO    MainThread:3555 [internal.py:wandb_internal():92] W&B internal server running at pid: 3555, started at: 2022-02-13 17:24:04.667189
2022-02-13 17:24:04,676 DEBUG   HandlerThread:3555 [handler.py:handle_request():131] handle_request: run_start
2022-02-13 17:24:04,677 INFO    WriterThread:3555 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220213_172403-uvzcjgoq/run-uvzcjgoq.wandb
2022-02-13 17:24:04,682 DEBUG   HandlerThread:3555 [meta.py:__init__():36] meta init
2022-02-13 17:24:04,683 DEBUG   HandlerThread:3555 [meta.py:__init__():50] meta init done
2022-02-13 17:24:04,683 DEBUG   HandlerThread:3555 [meta.py:probe():210] probe
2022-02-13 17:24:04,686 DEBUG   HandlerThread:3555 [meta.py:_setup_git():200] setup git
2022-02-13 17:24:04,715 DEBUG   HandlerThread:3555 [meta.py:_setup_git():207] setup git done
2022-02-13 17:24:04,715 DEBUG   HandlerThread:3555 [meta.py:_save_pip():54] save pip
2022-02-13 17:24:04,717 DEBUG   HandlerThread:3555 [meta.py:_save_pip():68] save pip done
2022-02-13 17:24:04,717 DEBUG   HandlerThread:3555 [meta.py:probe():248] probe done
2022-02-13 18:05:29,324 WARNING MainThread:3555 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-13 18:05:29,539 WARNING MainThread:3555 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-13 18:05:29,540 ERROR   MainThread:3555 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-13 18:05:29,771 INFO    WriterThread:3555 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220213_172403-uvzcjgoq/run-uvzcjgoq.wandb
2022-02-13 18:05:29,789 INFO    HandlerThread:3555 [handler.py:finish():739] shutting down handler
2022-02-13 18:05:30,204 INFO    SenderThread:3555 [sender.py:finish():1075] shutting down sender
2022-02-13 18:05:30,204 INFO    MainThread:3555 [internal.py:handle_exit():79] Internal process exited
