2022-02-14 15:37:36,918 INFO    MainThread:5503 [internal.py:wandb_internal():92] W&B internal server running at pid: 5503, started at: 2022-02-14 15:37:36.917709
2022-02-14 15:37:36,926 DEBUG   HandlerThread:5503 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 15:37:36,927 INFO    WriterThread:5503 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_153735-10hzs1w5/run-10hzs1w5.wandb
2022-02-14 15:37:36,933 DEBUG   HandlerThread:5503 [meta.py:__init__():36] meta init
2022-02-14 15:37:36,933 DEBUG   HandlerThread:5503 [meta.py:__init__():50] meta init done
2022-02-14 15:37:36,933 DEBUG   HandlerThread:5503 [meta.py:probe():210] probe
2022-02-14 15:37:36,936 DEBUG   HandlerThread:5503 [meta.py:_setup_git():200] setup git
2022-02-14 15:37:36,966 DEBUG   HandlerThread:5503 [meta.py:_setup_git():207] setup git done
2022-02-14 15:37:36,966 DEBUG   HandlerThread:5503 [meta.py:_save_pip():54] save pip
2022-02-14 15:37:36,968 DEBUG   HandlerThread:5503 [meta.py:_save_pip():68] save pip done
2022-02-14 15:37:36,968 DEBUG   HandlerThread:5503 [meta.py:probe():248] probe done
2022-02-14 15:51:16,116 WARNING MainThread:5503 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 15:51:16,555 WARNING MainThread:5503 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-14 15:51:16,555 ERROR   MainThread:5503 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-14 15:51:17,023 INFO    WriterThread:5503 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_153735-10hzs1w5/run-10hzs1w5.wandb
2022-02-14 15:51:17,028 INFO    HandlerThread:5503 [handler.py:finish():739] shutting down handler
2022-02-14 15:51:17,120 INFO    SenderThread:5503 [sender.py:finish():1075] shutting down sender
2022-02-14 15:51:17,122 INFO    MainThread:5503 [internal.py:handle_exit():79] Internal process exited
