2022-02-14 12:58:44,497 INFO    MainThread:2908 [internal.py:wandb_internal():92] W&B internal server running at pid: 2908, started at: 2022-02-14 12:58:44.496375
2022-02-14 12:58:44,505 DEBUG   HandlerThread:2908 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 12:58:44,505 INFO    WriterThread:2908 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_125842-lnydb6zi/run-lnydb6zi.wandb
2022-02-14 12:58:44,512 DEBUG   HandlerThread:2908 [meta.py:__init__():36] meta init
2022-02-14 12:58:44,512 DEBUG   HandlerThread:2908 [meta.py:__init__():50] meta init done
2022-02-14 12:58:44,512 DEBUG   HandlerThread:2908 [meta.py:probe():210] probe
2022-02-14 12:58:44,515 DEBUG   HandlerThread:2908 [meta.py:_setup_git():200] setup git
2022-02-14 12:58:44,544 DEBUG   HandlerThread:2908 [meta.py:_setup_git():207] setup git done
2022-02-14 12:58:44,545 DEBUG   HandlerThread:2908 [meta.py:_save_pip():54] save pip
2022-02-14 12:58:44,546 DEBUG   HandlerThread:2908 [meta.py:_save_pip():68] save pip done
2022-02-14 12:58:44,546 DEBUG   HandlerThread:2908 [meta.py:probe():248] probe done
2022-02-14 13:02:07,651 WARNING MainThread:2908 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 13:02:07,758 WARNING MainThread:2908 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-14 13:02:07,759 ERROR   MainThread:2908 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-14 13:02:08,298 INFO    WriterThread:2908 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_125842-lnydb6zi/run-lnydb6zi.wandb
2022-02-14 13:02:08,323 INFO    HandlerThread:2908 [handler.py:finish():739] shutting down handler
2022-02-14 13:02:08,559 INFO    SenderThread:2908 [sender.py:finish():1075] shutting down sender
2022-02-14 13:02:08,561 INFO    MainThread:2908 [internal.py:handle_exit():79] Internal process exited
