2022-02-13 17:18:55,254 INFO    MainThread:3504 [internal.py:wandb_internal():92] W&B internal server running at pid: 3504, started at: 2022-02-13 17:18:55.253570
2022-02-13 17:18:55,262 DEBUG   HandlerThread:3504 [handler.py:handle_request():131] handle_request: run_start
2022-02-13 17:18:55,263 INFO    WriterThread:3504 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220213_171853-38rfkrm0/run-38rfkrm0.wandb
2022-02-13 17:18:55,268 DEBUG   HandlerThread:3504 [meta.py:__init__():36] meta init
2022-02-13 17:18:55,270 DEBUG   HandlerThread:3504 [meta.py:__init__():50] meta init done
2022-02-13 17:18:55,270 DEBUG   HandlerThread:3504 [meta.py:probe():210] probe
2022-02-13 17:18:55,273 DEBUG   HandlerThread:3504 [meta.py:_setup_git():200] setup git
2022-02-13 17:18:55,303 DEBUG   HandlerThread:3504 [meta.py:_setup_git():207] setup git done
2022-02-13 17:18:55,303 DEBUG   HandlerThread:3504 [meta.py:_save_pip():54] save pip
2022-02-13 17:18:55,304 DEBUG   HandlerThread:3504 [meta.py:_save_pip():68] save pip done
2022-02-13 17:18:55,305 DEBUG   HandlerThread:3504 [meta.py:probe():248] probe done
2022-02-13 17:19:22,646 WARNING MainThread:3504 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-13 17:19:22,910 WARNING MainThread:3504 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-13 17:19:22,911 ERROR   MainThread:3504 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-13 17:19:23,275 INFO    SenderThread:3504 [sender.py:finish():1075] shutting down sender
2022-02-13 17:19:23,322 INFO    WriterThread:3504 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220213_171853-38rfkrm0/run-38rfkrm0.wandb
2022-02-13 17:19:23,349 INFO    HandlerThread:3504 [handler.py:finish():739] shutting down handler
2022-02-13 17:19:23,353 INFO    MainThread:3504 [internal.py:handle_exit():79] Internal process exited
