2022-02-14 18:22:35,419 INFO    MainThread:13399 [internal.py:wandb_internal():92] W&B internal server running at pid: 13399, started at: 2022-02-14 18:22:35.419097
2022-02-14 18:22:35,426 DEBUG   HandlerThread:13399 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 18:22:35,428 INFO    WriterThread:13399 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_182233-1hhod8c9/run-1hhod8c9.wandb
2022-02-14 18:22:35,434 DEBUG   HandlerThread:13399 [meta.py:__init__():36] meta init
2022-02-14 18:22:35,435 DEBUG   HandlerThread:13399 [meta.py:__init__():50] meta init done
2022-02-14 18:22:35,435 DEBUG   HandlerThread:13399 [meta.py:probe():210] probe
2022-02-14 18:22:35,438 DEBUG   HandlerThread:13399 [meta.py:_setup_git():200] setup git
2022-02-14 18:22:35,467 DEBUG   HandlerThread:13399 [meta.py:_setup_git():207] setup git done
2022-02-14 18:22:35,468 DEBUG   HandlerThread:13399 [meta.py:_save_pip():54] save pip
2022-02-14 18:22:35,469 DEBUG   HandlerThread:13399 [meta.py:_save_pip():68] save pip done
2022-02-14 18:22:35,469 DEBUG   HandlerThread:13399 [meta.py:probe():248] probe done
2022-02-14 18:32:36,712 WARNING MainThread:13399 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 18:32:37,206 WARNING MainThread:13399 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-14 18:32:37,207 ERROR   MainThread:13399 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-14 18:32:37,622 INFO    SenderThread:13399 [sender.py:finish():1075] shutting down sender
2022-02-14 18:32:37,802 INFO    HandlerThread:13399 [handler.py:finish():739] shutting down handler
2022-02-14 18:32:37,802 INFO    WriterThread:13399 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_182233-1hhod8c9/run-1hhod8c9.wandb
2022-02-14 18:32:37,808 INFO    MainThread:13399 [internal.py:handle_exit():79] Internal process exited
