2022-02-15 14:30:12,851 INFO    MainThread:19633 [internal.py:wandb_internal():92] W&B internal server running at pid: 19633, started at: 2022-02-15 14:30:12.850633
2022-02-15 14:30:12,858 DEBUG   HandlerThread:19633 [handler.py:handle_request():131] handle_request: run_start
2022-02-15 14:30:12,859 INFO    WriterThread:19633 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220215_143011-1lq8fyph/run-1lq8fyph.wandb
2022-02-15 14:30:12,866 DEBUG   HandlerThread:19633 [meta.py:__init__():36] meta init
2022-02-15 14:30:12,866 DEBUG   HandlerThread:19633 [meta.py:__init__():50] meta init done
2022-02-15 14:30:12,867 DEBUG   HandlerThread:19633 [meta.py:probe():210] probe
2022-02-15 14:30:12,870 DEBUG   HandlerThread:19633 [meta.py:_setup_git():200] setup git
2022-02-15 14:30:12,902 DEBUG   HandlerThread:19633 [meta.py:_setup_git():207] setup git done
2022-02-15 14:30:12,903 DEBUG   HandlerThread:19633 [meta.py:_save_pip():54] save pip
2022-02-15 14:30:12,904 DEBUG   HandlerThread:19633 [meta.py:_save_pip():68] save pip done
2022-02-15 14:30:12,904 DEBUG   HandlerThread:19633 [meta.py:probe():248] probe done
2022-02-15 14:46:50,557 WARNING MainThread:19633 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-15 14:46:51,266 WARNING MainThread:19633 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-15 14:46:51,267 ERROR   MainThread:19633 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-15 14:46:51,667 INFO    WriterThread:19633 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220215_143011-1lq8fyph/run-1lq8fyph.wandb
2022-02-15 14:46:51,673 INFO    HandlerThread:19633 [handler.py:finish():739] shutting down handler
2022-02-15 14:46:52,128 INFO    SenderThread:19633 [sender.py:finish():1075] shutting down sender
2022-02-15 14:46:52,130 INFO    MainThread:19633 [internal.py:handle_exit():79] Internal process exited
