2022-02-13 18:07:06,300 INFO    MainThread:3634 [internal.py:wandb_internal():92] W&B internal server running at pid: 3634, started at: 2022-02-13 18:07:06.299702
2022-02-13 18:07:06,307 DEBUG   HandlerThread:3634 [handler.py:handle_request():131] handle_request: run_start
2022-02-13 18:07:06,308 INFO    WriterThread:3634 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220213_180704-1bbj1wot/run-1bbj1wot.wandb
2022-02-13 18:07:06,315 DEBUG   HandlerThread:3634 [meta.py:__init__():36] meta init
2022-02-13 18:07:06,315 DEBUG   HandlerThread:3634 [meta.py:__init__():50] meta init done
2022-02-13 18:07:06,315 DEBUG   HandlerThread:3634 [meta.py:probe():210] probe
2022-02-13 18:07:06,318 DEBUG   HandlerThread:3634 [meta.py:_setup_git():200] setup git
2022-02-13 18:07:06,348 DEBUG   HandlerThread:3634 [meta.py:_setup_git():207] setup git done
2022-02-13 18:07:06,348 DEBUG   HandlerThread:3634 [meta.py:_save_pip():54] save pip
2022-02-13 18:07:06,349 DEBUG   HandlerThread:3634 [meta.py:_save_pip():68] save pip done
2022-02-13 18:07:06,349 DEBUG   HandlerThread:3634 [meta.py:probe():248] probe done
2022-02-13 18:13:54,369 WARNING MainThread:3634 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-13 18:13:54,800 WARNING MainThread:3634 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-13 18:13:54,800 ERROR   MainThread:3634 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-13 18:13:55,396 INFO    SenderThread:3634 [sender.py:finish():1075] shutting down sender
2022-02-13 18:13:55,739 INFO    WriterThread:3634 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220213_180704-1bbj1wot/run-1bbj1wot.wandb
2022-02-13 18:13:55,760 INFO    HandlerThread:3634 [handler.py:finish():739] shutting down handler
2022-02-13 18:13:55,762 INFO    MainThread:3634 [internal.py:handle_exit():79] Internal process exited
