2022-02-10 21:25:07,314 INFO    MainThread:1345 [internal.py:wandb_internal():92] W&B internal server running at pid: 1345, started at: 2022-02-10 21:25:07.313845
2022-02-10 21:25:07,323 DEBUG   HandlerThread:1345 [handler.py:handle_request():131] handle_request: run_start
2022-02-10 21:25:07,324 INFO    WriterThread:1345 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220210_212505-3meu4ukm/run-3meu4ukm.wandb
2022-02-10 21:25:07,330 DEBUG   HandlerThread:1345 [meta.py:__init__():36] meta init
2022-02-10 21:25:07,330 DEBUG   HandlerThread:1345 [meta.py:__init__():50] meta init done
2022-02-10 21:25:07,330 DEBUG   HandlerThread:1345 [meta.py:probe():210] probe
2022-02-10 21:25:07,333 DEBUG   HandlerThread:1345 [meta.py:_setup_git():200] setup git
2022-02-10 21:25:07,364 DEBUG   HandlerThread:1345 [meta.py:_setup_git():207] setup git done
2022-02-10 21:25:07,365 DEBUG   HandlerThread:1345 [meta.py:_save_pip():54] save pip
2022-02-10 21:25:07,366 DEBUG   HandlerThread:1345 [meta.py:_save_pip():68] save pip done
2022-02-10 21:25:07,366 DEBUG   HandlerThread:1345 [meta.py:probe():248] probe done
2022-02-10 21:33:14,833 WARNING MainThread:1345 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-10 21:33:15,593 WARNING MainThread:1345 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-10 21:33:15,594 ERROR   MainThread:1345 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-10 21:33:16,103 INFO    WriterThread:1345 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220210_212505-3meu4ukm/run-3meu4ukm.wandb
2022-02-10 21:33:16,111 INFO    HandlerThread:1345 [handler.py:finish():739] shutting down handler
2022-02-10 21:33:16,443 INFO    SenderThread:1345 [sender.py:finish():1075] shutting down sender
2022-02-10 21:33:16,445 INFO    MainThread:1345 [internal.py:handle_exit():79] Internal process exited
