2022-02-14 21:00:15,899 INFO    MainThread:3317 [internal.py:wandb_internal():92] W&B internal server running at pid: 3317, started at: 2022-02-14 21:00:15.898699
2022-02-14 21:00:15,907 DEBUG   HandlerThread:3317 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 21:00:15,908 INFO    WriterThread:3317 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_210014-1hh3icvs/run-1hh3icvs.wandb
2022-02-14 21:00:15,914 DEBUG   HandlerThread:3317 [meta.py:__init__():36] meta init
2022-02-14 21:00:15,914 DEBUG   HandlerThread:3317 [meta.py:__init__():50] meta init done
2022-02-14 21:00:15,914 DEBUG   HandlerThread:3317 [meta.py:probe():210] probe
2022-02-14 21:00:15,917 DEBUG   HandlerThread:3317 [meta.py:_setup_git():200] setup git
2022-02-14 21:00:15,946 DEBUG   HandlerThread:3317 [meta.py:_setup_git():207] setup git done
2022-02-14 21:00:15,947 DEBUG   HandlerThread:3317 [meta.py:_save_pip():54] save pip
2022-02-14 21:00:15,948 DEBUG   HandlerThread:3317 [meta.py:_save_pip():68] save pip done
2022-02-14 21:00:15,948 DEBUG   HandlerThread:3317 [meta.py:probe():248] probe done
2022-02-14 21:11:40,471 WARNING MainThread:3317 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 21:11:40,948 WARNING MainThread:3317 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-14 21:11:40,949 ERROR   MainThread:3317 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-14 21:11:41,084 INFO    SenderThread:3317 [sender.py:finish():1075] shutting down sender
2022-02-14 21:11:41,282 INFO    WriterThread:3317 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_210014-1hh3icvs/run-1hh3icvs.wandb
2022-02-14 21:11:41,307 INFO    HandlerThread:3317 [handler.py:finish():739] shutting down handler
2022-02-14 21:11:41,308 INFO    MainThread:3317 [internal.py:handle_exit():79] Internal process exited
