2022-02-10 20:44:39,892 INFO    MainThread:1105 [internal.py:wandb_internal():92] W&B internal server running at pid: 1105, started at: 2022-02-10 20:44:39.892180
2022-02-10 20:44:39,901 DEBUG   HandlerThread:1105 [handler.py:handle_request():131] handle_request: run_start
2022-02-10 20:44:39,901 INFO    WriterThread:1105 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220210_204438-11hrlkvk/run-11hrlkvk.wandb
2022-02-10 20:44:39,908 DEBUG   HandlerThread:1105 [meta.py:__init__():36] meta init
2022-02-10 20:44:39,908 DEBUG   HandlerThread:1105 [meta.py:__init__():50] meta init done
2022-02-10 20:44:39,909 DEBUG   HandlerThread:1105 [meta.py:probe():210] probe
2022-02-10 20:44:39,912 DEBUG   HandlerThread:1105 [meta.py:_setup_git():200] setup git
2022-02-10 20:44:39,943 DEBUG   HandlerThread:1105 [meta.py:_setup_git():207] setup git done
2022-02-10 20:44:39,944 DEBUG   HandlerThread:1105 [meta.py:_save_pip():54] save pip
2022-02-10 20:44:39,945 DEBUG   HandlerThread:1105 [meta.py:_save_pip():68] save pip done
2022-02-10 20:44:39,945 DEBUG   HandlerThread:1105 [meta.py:probe():248] probe done
2022-02-10 20:45:15,036 WARNING MainThread:1105 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-10 20:45:15,812 WARNING MainThread:1105 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-10 20:45:15,813 ERROR   MainThread:1105 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-10 20:45:15,916 INFO    SenderThread:1105 [sender.py:finish():1075] shutting down sender
2022-02-10 20:45:16,029 INFO    WriterThread:1105 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220210_204438-11hrlkvk/run-11hrlkvk.wandb
2022-02-10 20:45:16,036 INFO    HandlerThread:1105 [handler.py:finish():739] shutting down handler
2022-02-10 20:45:16,037 INFO    MainThread:1105 [internal.py:handle_exit():79] Internal process exited
