2022-02-13 23:43:46,475 INFO    MainThread:15122 [internal.py:wandb_internal():92] W&B internal server running at pid: 15122, started at: 2022-02-13 23:43:46.474852
2022-02-13 23:43:46,482 DEBUG   HandlerThread:15122 [handler.py:handle_request():131] handle_request: run_start
2022-02-13 23:43:46,483 INFO    WriterThread:15122 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220213_234344-a864c6ho/run-a864c6ho.wandb
2022-02-13 23:43:46,490 DEBUG   HandlerThread:15122 [meta.py:__init__():36] meta init
2022-02-13 23:43:46,490 DEBUG   HandlerThread:15122 [meta.py:__init__():50] meta init done
2022-02-13 23:43:46,490 DEBUG   HandlerThread:15122 [meta.py:probe():210] probe
2022-02-13 23:43:46,493 DEBUG   HandlerThread:15122 [meta.py:_setup_git():200] setup git
2022-02-13 23:43:46,523 DEBUG   HandlerThread:15122 [meta.py:_setup_git():207] setup git done
2022-02-13 23:43:46,523 DEBUG   HandlerThread:15122 [meta.py:_save_pip():54] save pip
2022-02-13 23:43:46,525 DEBUG   HandlerThread:15122 [meta.py:_save_pip():68] save pip done
2022-02-13 23:43:46,525 DEBUG   HandlerThread:15122 [meta.py:probe():248] probe done
2022-02-13 23:44:09,959 WARNING MainThread:15122 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-13 23:44:10,226 WARNING MainThread:15122 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-13 23:44:10,226 ERROR   MainThread:15122 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-13 23:44:10,492 INFO    SenderThread:15122 [sender.py:finish():1075] shutting down sender
2022-02-13 23:44:10,544 INFO    WriterThread:15122 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220213_234344-a864c6ho/run-a864c6ho.wandb
2022-02-13 23:44:10,562 INFO    HandlerThread:15122 [handler.py:finish():739] shutting down handler
2022-02-13 23:44:10,563 INFO    MainThread:15122 [internal.py:handle_exit():79] Internal process exited
