2022-02-15 13:05:36,426 INFO    MainThread:28904 [internal.py:wandb_internal():92] W&B internal server running at pid: 28904, started at: 2022-02-15 13:05:36.425477
2022-02-15 13:05:36,434 DEBUG   HandlerThread:28904 [handler.py:handle_request():131] handle_request: run_start
2022-02-15 13:05:36,435 INFO    WriterThread:28904 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220215_130534-2zpkcdud/run-2zpkcdud.wandb
2022-02-15 13:05:36,441 DEBUG   HandlerThread:28904 [meta.py:__init__():36] meta init
2022-02-15 13:05:36,441 DEBUG   HandlerThread:28904 [meta.py:__init__():50] meta init done
2022-02-15 13:05:36,441 DEBUG   HandlerThread:28904 [meta.py:probe():210] probe
2022-02-15 13:05:36,444 DEBUG   HandlerThread:28904 [meta.py:_setup_git():200] setup git
2022-02-15 13:05:36,474 DEBUG   HandlerThread:28904 [meta.py:_setup_git():207] setup git done
2022-02-15 13:05:36,474 DEBUG   HandlerThread:28904 [meta.py:_save_pip():54] save pip
2022-02-15 13:05:36,475 DEBUG   HandlerThread:28904 [meta.py:_save_pip():68] save pip done
2022-02-15 13:05:36,476 DEBUG   HandlerThread:28904 [meta.py:probe():248] probe done
2022-02-15 13:16:56,805 WARNING MainThread:28904 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-15 13:16:57,566 WARNING MainThread:28904 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-15 13:16:57,566 ERROR   MainThread:28904 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-15 13:16:57,609 INFO    SenderThread:28904 [sender.py:finish():1075] shutting down sender
2022-02-15 13:16:57,889 INFO    WriterThread:28904 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220215_130534-2zpkcdud/run-2zpkcdud.wandb
2022-02-15 13:16:57,909 INFO    HandlerThread:28904 [handler.py:finish():739] shutting down handler
2022-02-15 13:16:57,910 INFO    MainThread:28904 [internal.py:handle_exit():79] Internal process exited
