2022-02-11 17:45:28,387 INFO    MainThread:1101 [internal.py:wandb_internal():92] W&B internal server running at pid: 1101, started at: 2022-02-11 17:45:28.386719
2022-02-11 17:45:28,394 DEBUG   HandlerThread:1101 [handler.py:handle_request():131] handle_request: run_start
2022-02-11 17:45:28,395 INFO    WriterThread:1101 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220211_174526-1klae14j/run-1klae14j.wandb
2022-02-11 17:45:28,402 DEBUG   HandlerThread:1101 [meta.py:__init__():36] meta init
2022-02-11 17:45:28,403 DEBUG   HandlerThread:1101 [meta.py:__init__():50] meta init done
2022-02-11 17:45:28,403 DEBUG   HandlerThread:1101 [meta.py:probe():210] probe
2022-02-11 17:45:28,406 DEBUG   HandlerThread:1101 [meta.py:_setup_git():200] setup git
2022-02-11 17:45:28,436 DEBUG   HandlerThread:1101 [meta.py:_setup_git():207] setup git done
2022-02-11 17:45:28,437 DEBUG   HandlerThread:1101 [meta.py:_save_pip():54] save pip
2022-02-11 17:45:28,438 DEBUG   HandlerThread:1101 [meta.py:_save_pip():68] save pip done
2022-02-11 17:45:28,438 DEBUG   HandlerThread:1101 [meta.py:probe():248] probe done
2022-02-11 18:01:27,314 WARNING MainThread:1101 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-11 18:01:28,258 WARNING MainThread:1101 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-11 18:01:28,259 ERROR   MainThread:1101 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-11 18:01:28,684 INFO    SenderThread:1101 [sender.py:finish():1075] shutting down sender
2022-02-11 18:01:28,909 INFO    WriterThread:1101 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220211_174526-1klae14j/run-1klae14j.wandb
2022-02-11 18:01:28,919 INFO    HandlerThread:1101 [handler.py:finish():739] shutting down handler
2022-02-11 18:01:28,920 INFO    MainThread:1101 [internal.py:handle_exit():79] Internal process exited
