2022-02-14 11:13:22,098 INFO    MainThread:28243 [internal.py:wandb_internal():92] W&B internal server running at pid: 28243, started at: 2022-02-14 11:13:22.097788
2022-02-14 11:13:22,106 DEBUG   HandlerThread:28243 [handler.py:handle_request():131] handle_request: run_start
2022-02-14 11:13:22,107 INFO    WriterThread:28243 [datastore.py:open_for_write():77] open: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_111320-16ef028w/run-16ef028w.wandb
2022-02-14 11:13:22,113 DEBUG   HandlerThread:28243 [meta.py:__init__():36] meta init
2022-02-14 11:13:22,113 DEBUG   HandlerThread:28243 [meta.py:__init__():50] meta init done
2022-02-14 11:13:22,114 DEBUG   HandlerThread:28243 [meta.py:probe():210] probe
2022-02-14 11:13:22,116 DEBUG   HandlerThread:28243 [meta.py:_setup_git():200] setup git
2022-02-14 11:13:22,146 DEBUG   HandlerThread:28243 [meta.py:_setup_git():207] setup git done
2022-02-14 11:13:22,146 DEBUG   HandlerThread:28243 [meta.py:_save_pip():54] save pip
2022-02-14 11:13:22,148 DEBUG   HandlerThread:28243 [meta.py:_save_pip():68] save pip done
2022-02-14 11:13:22,148 DEBUG   HandlerThread:28243 [meta.py:probe():248] probe done
2022-02-14 11:22:44,233 WARNING MainThread:28243 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-14 11:22:44,693 WARNING MainThread:28243 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-14 11:22:44,693 ERROR   MainThread:28243 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-14 11:22:45,167 INFO    WriterThread:28243 [datastore.py:close():281] close: /home/pi/FedML-Server/executor/wandb/offline-run-20220214_111320-16ef028w/run-16ef028w.wandb
2022-02-14 11:22:45,190 INFO    HandlerThread:28243 [handler.py:finish():739] shutting down handler
2022-02-14 11:22:45,294 INFO    SenderThread:28243 [sender.py:finish():1075] shutting down sender
2022-02-14 11:22:45,295 INFO    MainThread:28243 [internal.py:handle_exit():79] Internal process exited
